defaults: &defaults
  mailer:
    authentication: "plain"
    address: "smtp.mailgun.org"
    port: 587
    domain: "sandbox804f7c5b265e414fa6fea420895c4621.mailgun.org"
    user_name: "postmaster@sandbox804f7c5b265e414fa6fea420895c4621.mailgun.org"
    password: "9c5913f939f618485d6a7cb9a305c5aa"
    admin_addresses:
      - "karol.lipski@gmail.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults